name: Generate Metrix

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-metrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Metrix GIF
        uses: joanroig/metrix@main
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }} # Do not change - uses PAT if available, otherwise uses GITHUB_TOKEN (public data only)
          GITHUB_USERNAME: '${{ github.actor }}' # Replace with your GitHub username if needed
          # FONT_PATH: 'assets/MxPlus_IBM_BIOS.ttf' # Path to the primary font file [currently unsupported unless you fork the repository to add the fonts]
          # SYMBOL_FONT_PATH: 'assets/MxPlus_IBM_BIOS.ttf' # Path to the font file used for symbols [currently unsupported unless you fork the repository to add the fonts]
          # TEXT_COLOR: 'random' # CSS color name, hex code, or one of: 'random', 'complementary', 'contrasting', 'shade'
          # BACKGROUND_COLOR: 'random' # Same options as TEXT_COLOR
          # MINIMUM_CONTRAST: '2' # Minimum contrast ratio (1 to 21)
          # TITLE_SUFFIX: "'s GitHub Metrix" # Suffix text shown after username
          # ACTIVITY_TEXT: 'Last month commit activity:' # Header text in the graphic
          # ACTIVITY_DAYS: '30' # Number of days to visualize
          # LOOP: 'false' # Whether to loop the GIF infinitely
          # WIDTH: '622' # Width of the output GIF
          # HEIGHT: '350' # Height of the output GIF
          # GLITCHES: 'true' # Whether to enable visual glitches
