name: Generate Metrix

on:
  schedule:
    - cron: '0 0 * * *' # Default schedule, runs everyevery day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-metrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Metrix GIF
        uses: joanroig/metrix@main
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: 'joanroig'
          # FONT_PATH: 'assets/MxPlus_IBM_BIOS.ttf'
          # SYMBOL_FONT_PATH: 'assets/MxPlus_IBM_BIOS.ttf'
          TEXT_COLOR: 'random'
          BACKGROUND_COLOR: 'random'
          MINIMUM_CONTRAST: '2'
          TITLE_SUFFIX: "'s GitHub Stats"
          # ACTIVITY_TEXT: 'Last month commit activity:'
          # ACTIVITY_DAYS: '30'
          # LOOP: 'false'
          # WIDTH: '622'
          # HEIGHT: '350'
          # GLITCHES: 'true'
